# Generated by Django 2.0.5 on 2018-05-09 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
